# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 17:10


import deploy.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='impex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='impex|name')),
                ('description', models.TextField(max_length=500, verbose_name='impex|description')),
                ('packagesum', models.CharField(blank=True, max_length=40, null=True, verbose_name='impex|packagesum')),
                ('filename', models.FileField(blank=True, default=None, null=True, upload_to=deploy.models.content_file_name, verbose_name='impex|filename')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='impex|date')),
                ('exclusive_editor', models.CharField(choices=[(b'yes', 'package|yes'), (b'no', 'package|no')], default=b'no', max_length=3, verbose_name='impex|exclusive editor')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'impex|import/export',
                'verbose_name_plural': 'impex|imports/exports',
            },
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='package|name')),
                ('description', models.CharField(max_length=500, verbose_name='package|description')),
                ('command', models.TextField(help_text='package|command help text', max_length=1000, verbose_name='package|command')),
                ('packagesum', models.CharField(blank=True, max_length=40, null=True, verbose_name='package|packagesum')),
                ('filename', models.FileField(blank=True, null=True, upload_to=deploy.models.content_file_name, verbose_name='package|filename')),
                ('ignoreperiod', models.CharField(choices=[(b'yes', 'package|yes'), (b'no', 'package|no')], default=b'no', max_length=3, verbose_name='package|ignore deploy period')),
                ('public', models.CharField(choices=[(b'yes', 'package|yes'), (b'no', 'package|no')], default=b'no', max_length=3, verbose_name='package| public package')),
                ('exclusive_editor', models.CharField(choices=[(b'yes', 'package|yes'), (b'no', 'package|no')], default=b'no', max_length=3, verbose_name='package|exclusive editor')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'package|deployment package',
                'verbose_name_plural': 'package|deployment packages',
            },
        ),
        migrations.CreateModel(
            name='packagecondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='packagecondition|name')),
                ('depends', models.CharField(choices=[(b'installed', 'installed'), (b'notinstalled', 'notinstalled'), (b'lower', 'lower'), (b'higher', 'higher'), (b'system_is', 'operating_system_is'), (b'system_not', 'operating_system_not'), (b'is_W64_bits', 'is_W64_bits'), (b'is_W32_bits', 'is_W32_bits'), (b'language_is', 'language_is')], default=b'installed', max_length=12, verbose_name='packagecondition|depends')),
                ('softwarename', models.CharField(blank=True, default=b'undefined', help_text='packagecondition|softwarename help text', max_length=100, null=True, verbose_name='packagecondition|softwarename')),
                ('softwareversion', models.CharField(blank=True, default=b'undefined', help_text='packagecondition|softwareversion help text', max_length=500, null=True, verbose_name='packagecondition|softwareversion')),
                ('exclusive_editor', models.CharField(choices=[(b'yes', 'package|yes'), (b'no', 'package|no')], default=b'no', max_length=3, verbose_name='packagecondition|exclusive editor')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'packagecondition|package condition',
                'verbose_name_plural': 'packagecondition|packages conditions',
            },
        ),
        migrations.CreateModel(
            name='packagehistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='packagehistory|name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='packagehistory|description')),
                ('command', models.TextField(blank=True, max_length=1000, null=True, verbose_name='packagehistory|command')),
                ('packagesum', models.CharField(blank=True, max_length=40, null=True, verbose_name='packagehistory|packagesum')),
                ('filename', models.CharField(blank=True, max_length=500, null=True, verbose_name='packagehistory|filename')),
                ('status', models.CharField(blank=True, default=b'Programmed', max_length=500, null=True, verbose_name='packagehistory|status')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='packagehistory|date')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'packagehistory|package history',
                'verbose_name_plural': 'packagehistory|packages history',
            },
        ),
        migrations.CreateModel(
            name='packageprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='packageprofile|name')),
                ('description', models.CharField(max_length=500, verbose_name='packageprofile|description')),
                ('exclusive_editor', models.CharField(choices=[(b'yes', 'package|yes'), (b'no', 'package|no')], default=b'no', max_length=3, verbose_name='packageprofile|exclusive editor')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'packageprofile|package profile',
                'verbose_name_plural': 'packageprofile|packages profiles',
            },
        ),
        migrations.CreateModel(
            name='packagewakeonlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='packagewakeonlan|packagewakeonlan help text', max_length=100, unique=True, verbose_name='packagewakeonlan|name')),
                ('description', models.CharField(max_length=500, verbose_name='packagewakeonlan|description')),
                ('date', models.DateTimeField(verbose_name='packagewakeonlan|start_time')),
                ('status', models.CharField(choices=[(b'Programmed', 'packagewakeonlan|Programmed'), (b'Completed', 'packagewakeonlan|Completed')], default=b'Programmed', max_length=100, verbose_name='packagewakeonlan|status')),
                ('exclusive_editor', models.CharField(choices=[(b'yes', 'package|yes'), (b'no', 'package|no')], default=b'no', max_length=3, verbose_name='packagewakonelan|exclusive editor')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'packagewakeonlan|package wakeonlan',
                'verbose_name_plural': 'packagewakeonlan|packages wakeonlan',
            },
        ),
        migrations.CreateModel(
            name='timeprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='timeprofile|timeprofile help text', max_length=100, verbose_name='timeprofile|name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='timeprofile|description')),
                ('start_time', models.TimeField(verbose_name='timeprofile|start_time')),
                ('end_time', models.TimeField(verbose_name='timeprofile|end_time')),
                ('exclusive_editor', models.CharField(choices=[(b'yes', 'package|yes'), (b'no', 'package|no')], default=b'no', max_length=3, verbose_name='timeprofile|exclusive editor')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='timeprofile| condition last editor')),
            ],
            options={
                'ordering': ['start_time'],
                'verbose_name': 'timeprofile|time profile',
                'verbose_name_plural': 'timeprofile|time profiles',
            },
        ),
    ]
