# Generated by Django 4.2.11 on 2024-04-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_alter_packagecondition_depends'),
    ]

    operations = [
        migrations.AddField(
            model_name='impex',
            name='packagehash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='package|packagehash'),
        ),
        migrations.AddField(
            model_name='package',
            name='packagehash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='package|packagehash'),
        ),
        migrations.AddField(
            model_name='packagehistory',
            name='packagehash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='package|packagehash'),
        ),
    ]
