# Generated by Django 4.2.11 on 2024-04-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_impex_packagehash_package_packagehash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='use_global_variables',
            field=models.CharField(choices=[('yes', 'package|yes'), ('no', 'package|no')], default='no', help_text='package|global variables help text', max_length=3, verbose_name='package|global variables'),
        ),
        migrations.CreateModel(
            name='packagecustomvar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='packagecustomvar|name help text', max_length=100, verbose_name='name')),
                ('value', models.CharField(max_length=200, verbose_name='value')),
                ('apply_on_commands', models.BooleanField(default=True, verbose_name='packagecustomvar|apply on commands')),
                ('apply_on_conditions', models.BooleanField(default=True, verbose_name='packagecustomvar|apply on conditions')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.package', verbose_name='package|deployment package')),
            ],
            options={
                'verbose_name': 'package|deployment custom variable',
                'verbose_name_plural': 'package|deployment custom variables',
                'unique_together': {('name', 'package')},
            },
        ),
    ]
