# Generated by Django 4.2.11 on 2024-05-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_package_timeprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagecondition',
            name='depends',
            field=models.CharField(choices=[('installed', 'installed'), ('notinstalled', 'notinstalled'), ('lower', 'lower'), ('higher', 'higher'), ('system_is', 'operating_system_is'), ('system_not', 'operating_system_not'), ('is_W64_bits', 'is_W64_bits'), ('is_W32_bits', 'is_W32_bits'), ('language_is', 'language_is'), ('hostname_in', 'hostname_in'), ('hostname_not', 'hostname_not'), ('username_in', 'username_in'), ('username_not', 'username_not'), ('ipaddr_in', 'ipaddr_in'), ('ipaddr_not', 'ipaddr_not'), ('vendor_in', 'vendor_in'), ('vendor_not', 'vendor_not'), ('product_in', 'product_in'), ('product_not', 'product_not'), ('type_in', 'type_in'), ('type_not', 'type_not'), ('isfile', 'isfile'), ('notisfile', 'notisfile'), ('isdir', 'isdir'), ('notisdir', 'notisdir'), ('isfiledir', 'isfiledir'), ('notisfiledir', 'notisfiledir'), ('hashis', 'hashis'), ('hashnot', 'hashnot'), ('exitcodeis', 'exitcodeis'), ('exitcodenot', 'exitcodenot'), ('executetimes', 'executetimes'), ('installtimes', 'installtimes'), ('executedelay', 'executedelay'), ('installdelay', 'installdelay')], default='installed', help_text='packagecondition|depends help text', max_length=12, verbose_name='packagecondition|depends'),
        ),
    ]
