# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deployconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='deployconfig|name')),
                ('activate_deploy', models.CharField(choices=[(b'yes', 'yes'), (b'no', 'no')], default=b'yes', max_length=3, verbose_name='deployconfig|activate_deploy')),
                ('activate_time_deploy', models.CharField(choices=[(b'yes', 'yes'), (b'no', 'no')], default=b'no', max_length=3, verbose_name='deployconfig|activate_time_deploy')),
                ('start_time', models.TimeField(verbose_name='deployconfig|start_time')),
                ('end_time', models.TimeField(verbose_name='deployconfig|end_time')),
            ],
            options={
                'verbose_name': 'deployconfig|deployconfig',
                'verbose_name_plural': 'deployconfig|deployconfigs',
            },
        ),
        migrations.CreateModel(
            name='globalconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'default', max_length=100, verbose_name='globalconfig|name')),
                ('show_warning', models.CharField(choices=[(b'yes', 'yes'), (b'no', 'no')], default=b'no', help_text='globalconfig|show_warning help text', max_length=3, verbose_name='globalconfig|show_warning')),
                ('remove_duplicate', models.CharField(choices=[(b'yes', 'yes'), (b'no', 'no')], default=b'no', help_text='globalconfig|remove_duplicate help text', max_length=3, verbose_name='globalconfig|remove_duplicate')),
            ],
            options={
                'verbose_name': 'globalconfig|globalconfig',
                'verbose_name_plural': 'globalconfig|globalconfigs',
            },
        ),
        migrations.CreateModel(
            name='subuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'subuser|entity',
                'verbose_name_plural': 'subuser|entity',
            },
        ),
    ]
