# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 17:10


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='entity',
            field=models.ManyToManyField(blank=True, default=None, to='inventory.entity', verbose_name='entity|entity'),
        ),
        migrations.AddField(
            model_name='subuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deployconfig',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.entity', verbose_name='deployconfig|entity'),
        ),
        migrations.AddField(
            model_name='deployconfig',
            name='packageprofile',
            field=models.ForeignKey(blank=True, default=None, help_text='machine|packages profile help text', null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.packageprofile', verbose_name='deployconfig|package profile'),
        ),
        migrations.AddField(
            model_name='deployconfig',
            name='timeprofile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.timeprofile', verbose_name='deployconfig|time deploy profile'),
        ),
    ]
