# Generated by Django 3.2 on 2022-04-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20180605_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployconfig',
            name='activate_deploy',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3, verbose_name='deployconfig|activate_deploy'),
        ),
        migrations.AlterField(
            model_name='deployconfig',
            name='activate_time_deploy',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3, verbose_name='deployconfig|activate_time_deploy'),
        ),
        migrations.AlterField(
            model_name='deployconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='name',
            field=models.CharField(default='default', max_length=100, verbose_name='globalconfig|name'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='remove_duplicate',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', help_text='globalconfig|remove_duplicate help text', max_length=3, verbose_name='globalconfig|remove_duplicate'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='show_warning',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', help_text='globalconfig|show_warning help text', max_length=3, verbose_name='globalconfig|show_warning'),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
