# Generated by Django 4.2.7 on 2024-03-27 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0003_auto_20220411_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='userauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_auth', models.BooleanField(default=False, verbose_name='LDAP')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userauth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authentication profile',
                'verbose_name_plural': 'Authentication profile',
            },
        ),
    ]
