# Generated by Django 4.2.11 on 2024-05-18 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_userauth_apply_to_existing'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployconfig',
            name='download_no_restart',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', help_text='deployconfig|download_no_restart help text', max_length=3, verbose_name='deployconfig|download_no_restart'),
        ),
        migrations.AddField(
            model_name='deployconfig',
            name='install_timeout',
            field=models.PositiveIntegerField(default=600, help_text='deployconfig|install_timeout help text', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='deployconfig|install_timeout'),
        ),
        migrations.AddField(
            model_name='deployconfig',
            name='no_break_on_error',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', help_text='deployconfig|no_break_on_error help text', max_length=3, verbose_name='deployconfig|no_break_on_error'),
        ),
    ]
