# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='entity|name')),
                ('description', models.TextField(max_length=1000, verbose_name='entity|description')),
                ('force_packageprofile', models.CharField(choices=[(b'yes', 'yes'), (b'no', 'no')], default=b'no', max_length=3, verbose_name='entity|force_packageprofile')),
                ('force_timeprofile', models.CharField(choices=[(b'yes', 'yes'), (b'no', 'no')], default=b'no', max_length=3, verbose_name='entity|force_timeprofile')),
                ('redistrib_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='entity|redistrib_url')),
                ('ip_range', models.CharField(blank=True, help_text='entity|ip range help text', max_length=200, null=True, verbose_name='entity|ip_range')),
                ('old_packageprofile', models.ForeignKey(blank=True, help_text='entity|old packages profile help text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_packageprofile', to='deploy.packageprofile', verbose_name='entity|old package profile')),
                ('old_timeprofile', models.ForeignKey(blank=True, help_text='entity|old time profile help text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_timeprofile', to='deploy.timeprofile', verbose_name='entity|old time profile')),
                ('packageprofile', models.ForeignKey(blank=True, help_text='entity|packages profile help text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pprofile', to='deploy.packageprofile', verbose_name='entity|package profile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='inventory.entity', verbose_name='entity|parent')),
                ('timeprofile', models.ForeignKey(blank=True, help_text='entity|time profile help text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeprofile', to='deploy.timeprofile', verbose_name='entity|time profile')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'entity|entity',
                'verbose_name_plural': 'entity|entities',
            },
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100, verbose_name='machine|serial')),
                ('name', models.CharField(max_length=100, verbose_name='machine|name')),
                ('vendor', models.CharField(blank=True, default=b'undefined', max_length=100, null=True, verbose_name='machine|vendor')),
                ('product', models.CharField(blank=True, default=b'undefined', max_length=100, null=True, verbose_name='machine|product')),
                ('domain', models.CharField(blank=True, default=b'undefined', max_length=100, null=True, verbose_name='machine|domain')),
                ('uuid', models.CharField(blank=True, default=b'undefined', max_length=100, null=True, verbose_name='machine|uuid')),
                ('username', models.CharField(blank=True, default=b'undefined', max_length=100, null=True, verbose_name='machine|username')),
                ('language', models.CharField(blank=True, default=b'undefined', max_length=100, null=True, verbose_name='machine|language')),
                ('lastsave', models.DateTimeField(blank=True, null=True, verbose_name='machine|lastsave')),
                ('netsum', models.CharField(blank=True, max_length=40, null=True, verbose_name='machine|netsum')),
                ('ossum', models.CharField(blank=True, max_length=40, null=True, verbose_name='machine|ossum')),
                ('softsum', models.CharField(blank=True, max_length=40, null=True, verbose_name='machine|softsum')),
                ('manualy_created', models.CharField(choices=[(b'yes', 'yes'), (b'no', 'no')], default=b'yes', max_length=3, verbose_name='machine|manualy_created')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='machine|comment')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.entity', verbose_name='machine|entity')),
                ('packageprofile', models.ForeignKey(blank=True, help_text='machine|packages profile help text', null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.packageprofile', verbose_name='machine|package profile')),
                ('packages', models.ManyToManyField(blank=True, to='deploy.package', verbose_name='machine|packages')),
                ('timeprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.timeprofile', verbose_name='machine|time deploy profile')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'machine|machine',
                'verbose_name_plural': 'machine|machines',
            },
        ),
        migrations.CreateModel(
            name='net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='net|ip')),
                ('mask', models.CharField(max_length=50, verbose_name='net|mask')),
                ('mac', models.CharField(max_length=100, verbose_name='net|mac')),
                ('manualy_created', models.CharField(choices=[(b'yes', 'yes'), (b'no', 'no')], default=b'yes', max_length=3, verbose_name='net|manualy_created')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.machine', verbose_name='net|host')),
            ],
            options={
                'verbose_name': 'net|network',
                'verbose_name_plural': 'net|networks',
            },
        ),
        migrations.CreateModel(
            name='osdistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='osdistribution|name')),
                ('version', models.CharField(blank=True, default=b'undefined', max_length=100, null=True, verbose_name='osdistribution|version')),
                ('arch', models.CharField(blank=True, max_length=100, null=True, verbose_name='osdistribution|arch')),
                ('systemdrive', models.CharField(blank=True, max_length=100, null=True, verbose_name='osdistribution|systemdrive')),
                ('manualy_created', models.CharField(choices=[(b'yes', 'yes'), (b'no', 'no')], default=b'yes', max_length=3, verbose_name='osdistribution|manualy_created')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.machine', verbose_name='osdistribution|host')),
            ],
            options={
                'verbose_name': 'osdistribution|osdistribution',
                'verbose_name_plural': 'osdistribution|osdistributions',
            },
        ),
        migrations.CreateModel(
            name='software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='software|name')),
                ('version', models.CharField(blank=True, default=b'undefined', max_length=500, null=True, verbose_name='software|version')),
                ('uninstall', models.CharField(blank=True, default=b'undefined', max_length=500, null=True, verbose_name='software|uninstall')),
                ('manualy_created', models.CharField(choices=[(b'yes', 'yes'), (b'no', 'no')], default=b'yes', max_length=3, verbose_name='software|manualy_created')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.machine', verbose_name='software|host')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'software|software',
                'verbose_name_plural': 'software|softwares',
            },
        ),
        migrations.CreateModel(
            name='typemachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='typemachine|name')),
            ],
            options={
                'verbose_name': 'typemachine|typemachine',
                'verbose_name_plural': 'typemachine|typesofmachines',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='typemachine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.typemachine', verbose_name='machine|typemachine'),
        ),
    ]
