# Generated by Django 3.2 on 2022-04-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='force_packageprofile',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3, verbose_name='entity|force_packageprofile'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='force_timeprofile',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3, verbose_name='entity|force_timeprofile'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='domain',
            field=models.CharField(blank=True, default='undefined', max_length=100, null=True, verbose_name='machine|domain'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='language',
            field=models.CharField(blank=True, default='undefined', max_length=100, null=True, verbose_name='machine|language'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='manualy_created',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3, verbose_name='machine|manualy_created'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='product',
            field=models.CharField(blank=True, default='undefined', max_length=100, null=True, verbose_name='machine|product'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='username',
            field=models.CharField(blank=True, default='undefined', max_length=100, null=True, verbose_name='machine|username'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='uuid',
            field=models.CharField(blank=True, default='undefined', max_length=100, null=True, verbose_name='machine|uuid'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='vendor',
            field=models.CharField(blank=True, default='undefined', max_length=100, null=True, verbose_name='machine|vendor'),
        ),
        migrations.AlterField(
            model_name='net',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='net',
            name='manualy_created',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3, verbose_name='net|manualy_created'),
        ),
        migrations.AlterField(
            model_name='osdistribution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='osdistribution',
            name='manualy_created',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3, verbose_name='osdistribution|manualy_created'),
        ),
        migrations.AlterField(
            model_name='osdistribution',
            name='version',
            field=models.CharField(blank=True, default='undefined', max_length=100, null=True, verbose_name='osdistribution|version'),
        ),
        migrations.AlterField(
            model_name='software',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='software',
            name='manualy_created',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3, verbose_name='software|manualy_created'),
        ),
        migrations.AlterField(
            model_name='software',
            name='uninstall',
            field=models.CharField(blank=True, default='undefined', max_length=500, null=True, verbose_name='software|uninstall'),
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.CharField(blank=True, default='undefined', max_length=500, null=True, verbose_name='software|version'),
        ),
        migrations.AlterField(
            model_name='typemachine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
